import { BoardPage } from "@/features/board/board.page";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div style={{ height: "50px" }}>header</div>
        <BoardPage />
      </div>
    </>
  );
}
